/* eslint-disable @typescript-eslint/naming-convention */
/* eslint-disable no-param-reassign */
import { existsSync } from 'fs';

import { Command } from '@commander-js/extra-typings';
import chalk from 'chalk';
import open from 'open';
import prompts, { PromptObject } from 'prompts';

import { DeviceCodeGrant, ImplicitGrant } from '@/services/auth';
import { EXPIRES_IN, link } from '@/utils';
import { PCS_CONF } from '@/utils/constants';
import { writeJSON } from '@/utils/json';

/** 获取 access token by conf file */
export async function getAccessToken(options: ReturnType<typeof initCommand.opts>) {
  const oauth = new ImplicitGrant({
    client_id: options.key,
    client_secret: options.secret,
  });
  const authorizeURL = oauth.getAuthorizeURL();
  await open(authorizeURL);

  console.log(chalk.hex('#FFA500')('You\'ll have to grab the access_token generated by Baidu.'));
  console.log('');
  console.log(`1. Visit ${link(authorizeURL, authorizeURL)}`);
  console.log('2. After the page is being redirected (it should show something like OAuth 2.0), copy the current URL to your favorite text editor');
  console.log('3. Grab the access_token part, take only the part between "access_token=" and the next "&" symbol (without quotes).');
  console.log('4. Copy it and paste here, then press Enter.');

  const { access_token } = await prompts({
    type: 'text',
    name: 'access_token',
    message: 'access_token',
  });

  const accessTokenCreateTime = Date.now();

  if (access_token) {
    const expireSecond = (Date.now() - accessTokenCreateTime) / 1000;
    const expires_in = EXPIRES_IN - expireSecond;

    // 保存配置
    await writeJSON(PCS_CONF, { ...options, access_token, expires_in });
  }
}

async function getAccessTokenByDeviceCode(options: ReturnType<typeof initCommand.opts>) {
  const oauth = new DeviceCodeGrant({
    client_id: options.key,
    client_secret: options.secret,
  });

  const deviceCode = await oauth.getDeviceCode();
  const authorizeURL = oauth.getAuthorizeURL(deviceCode);

  console.log('Launch your favorite web browser and visit: ');
  console.log(link(authorizeURL, authorizeURL));
  console.log(`Input ${chalk.bold.red(deviceCode.user_code)} as the user code if asked.`);
  console.log('After granting access to the application, come back here and ');

  await open(authorizeURL);

  const { confirm } = await prompts({
    type: 'confirm',
    name: 'confirm',
    message: 'Press Enter to continue',
    initial: true,
  });

  if (confirm) {
    const oauthTokenResponse = await oauth.authorize(deviceCode.device_code);
    console.log(chalk.green('Successfully initialized'));
    console.log(`access_token: ${chalk.yellowBright(oauthTokenResponse.access_token)}`);
    console.log(`refresh_token: ${chalk.yellowBright(oauthTokenResponse.refresh_token)}`);

    return oauthTokenResponse;
  }
}

export const initCommand = new Command('init')
  .description('initialize baidu pcs')
  .option('-n, --name <string>', 'app name', '')
  .option('-k, --key <string>', 'app key', '')
  .option('-s, --secret <string>', 'app secret', '')
  .action(async (options) => {
    // 如果存在 则提示是否覆盖
    if (existsSync(PCS_CONF)) {
      const { confirm } = await prompts({
        type: 'confirm',
        name: 'confirm',
        message: 'Baidu pcs initialization will be begin. If you have already configured before, your old settings will be overwritten. Can you confirm?',
        initial: false,
      });
      if (!confirm) {
        return;
      }
    }

    // 设备码模式授权
    const questions: PromptObject[] = [];
    (['name', 'key', 'secret'] as const).forEach((item) => {
      if (!options[item]) {
        questions.push({
          type: 'text',
          name: item,
          message: `Please enter baidu app ${item}`,
        });
      }
    });
    options = { ...options, ...await prompts(questions) };
    if (!options.key || !options.secret) {
      return;
    }

    // 如果token存在且没有过期, 则提示用户是否要继续初始化
    // const tokenJson = fileJSON('TOKEN');
    // if (tokenJson && tokenJson.access_token) {
    //   log(`Your access token has not expired (expiration date: ${dayjs(tokenJson.expires_time).format('YYYY-MM-DD HH:mm:ss')}).`);
    //   const { value } = await prompts({
    //     type: 'confirm',
    //     name: 'value',
    //     message: 'Do you want to continue initializing?',
    //     initial: false,
    //   });

    //   if (!value) {
    //     return;
    //   }
    // }

    // // 如果 user_code 存在且没有过期，提示用户是否要用当前app信息生成token
    // const deviceJson = fileJSON('DEVICE');
    // if (deviceJson) {
    //   await getAccessTokenByDeviceCode(deviceJson);
    //   return;
    // }

    const token = await getAccessTokenByDeviceCode(options);
    if (!token) {
      return;
    }

    // 保存配置
    await writeJSON(PCS_CONF, { ...options, ...token });
  });
